### ISSUE TITLE
Loading the example preset "002_custom_image_and_custom_module.json" is not working

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV-Workshop#4]
When you load `presets/002_custom_image_and_custom_module.json`  and DON't have the required modules, the preset is broken.

**Comment by 2xAA** [comment]
@TimPietrusky Can we transfer this issue to https://github.com/vcync/modV?
Or at least document this issue over there as it’s a modV bug, not a workshop bug.

**Comment by TimPietrusky** [comment]
Will be handled via https://github.com/vcync/modV/issues/660
